// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGy8jGyu3Wf2yJIVR0cPf7GyMlZk-KunA',
    appId: '1:812436734342:web:aff3a37fb53f2be51e2c07',
    messagingSenderId: '812436734342',
    projectId: 'portifolio-app22-notification',
    authDomain: 'portifolio-app22-notification.firebaseapp.com',
    storageBucket: 'portifolio-app22-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvEoS0YqSYrIDWKOYhJX8i_qC6_Lug-4',
    appId: '1:812436734342:android:91067721dada81ac1e2c07',
    messagingSenderId: '812436734342',
    projectId: 'portifolio-app22-notification',
    storageBucket: 'portifolio-app22-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyRyA2cN8mv_H1WZkvYuVm4uKcxvlqXjY',
    appId: '1:812436734342:ios:97b761c81999c5c21e2c07',
    messagingSenderId: '812436734342',
    projectId: 'portifolio-app22-notification',
    storageBucket: 'portifolio-app22-notification.appspot.com',
    iosClientId: '812436734342-17qo366fkqfcmr863tcnbfgeavigv0e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyRyA2cN8mv_H1WZkvYuVm4uKcxvlqXjY',
    appId: '1:812436734342:ios:97b761c81999c5c21e2c07',
    messagingSenderId: '812436734342',
    projectId: 'portifolio-app22-notification',
    storageBucket: 'portifolio-app22-notification.appspot.com',
    iosClientId: '812436734342-17qo366fkqfcmr863tcnbfgeavigv0e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotifications',
  );
}
